[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/content/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/dsa/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
